site_name: Moje projekty
site_author: Rafał Okroj
site_description: >
  Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: Himap-3478/ds_ai_portfolio
repo_url: https://github.com/Himap-3478/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: indigo

nav:
  - Strona Domowa: index.md
  - Obecny projekt:
      - "Matejko": Generator_kolorowanek/index.md
  - Poprzednie projekty:
      - "Iris": Irysy/index.md
      - "Titanic": Titanic/index.md
      - "Ceny mieszkań": Ceny_mieszkan/index.md